[package]
name = "grafbabe"
version = "0.1.0"
authors = ["Jess Bees"]
edition = "2024"
rust-version = "1.95"
description = "Simple openmetrics stats collector"
repository = "https://github.com/toomanybees/grafbabe"
license-file = "LICENSE.txt"
keywords = ["metrics", "prometheus", "openmetrics", "dashboard", "graph"]
categories = ["command-line-utilities", "visualization"]

[dependencies]
httparse = "1.10.1"
env_logger = { version = "0.11.11", default-features = false, features = ["auto-color", "kv"] }
http = "1.4.2"
include_str_etag = { path = "./include_str_etag" }
log = { version = "0.4.33", features = ["kv"] }
mio = { version = "1.2.0", features = ["net", "os-poll"] }
prometheus-scraper = { version = "0.1.2", default-features = false }
rusqlite = { version = "0.40.1", default-features = false, features = ["array", "vtab"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "3.3.0", default-features = false, features = ["gzip"] }

[features]
default = ["bundled_sqlite"]
bundled_sqlite = ["rusqlite/bundled"]
mock_data = []
tls = ["ureq/rustls"]
