[package]
name = "grafbabe"
version = "0.1.1"
authors = ["Jess Bees"]
edition = "2024"
rust-version = "1.95"
description = "Simple openmetrics stats collector"
repository = "https://github.com/toomanybees/grafbabe"
license-file = "LICENSE.txt"
keywords = ["metrics", "prometheus", "openmetrics", "dashboard", "graph"]
categories = ["command-line-utilities", "visualization"]

[dependencies]
anstyle = { version = "1.0.14", optional = true }
env_logger = { version = "0.11.11", default-features = false, features = ["kv"] }
grafbabe_macros = { path = "./grafbabe_macros", version = "0.0.0" }
http = "1.4.2"
httparse = "1.10.1"
log = { version = "0.4.33", features = ["kv"] }
mio = { version = "1.2.0", features = ["net", "os-poll"] }
prometheus-scraper = { version = "0.1.2", default-features = false }
rusqlite = { version = "0.40.1", default-features = false, features = ["array", "vtab"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "3.3.0", default-features = false, features = ["gzip"] }

[features]
default = ["bundled_sqlite", "color"]
bundled_sqlite = ["rusqlite/bundled"]
color = ["dep:anstyle", "env_logger/auto-color"]
mock_data = []
tls = ["ureq/rustls"]
