name: Build for release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUSTUP_CHANNEL: "1.97"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # default-features: [true, false]
        os:
          - image: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
            compress-command: "tar -czvf"
            asset-extension: "tgz"
          - image: "macos-latest"
            target: "aarch64-apple-darwin"
            compress-compand: "tar -czvf"
            asset-extension: "tgz"
          - image: "windows-latest"
            target: "x86_64-pc-windows-msvc"
            compress-command: "7z a -tzip"
            asset-extension: "zip"
    name: Build ${{ matrix.os.target }}
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: |
          rustup install "$RUSTUP_CHANNEL" --profile=minimal && rustup default "$RUSTUP_CHANNEL"
      - name: Build
        run: cargo build --release --locked
      - name: Compress
        run: |
          cd target/release
          ${{ matrix.os.compress-command }} "grafbabe.${{ matrix.os.target }}.${{ matrix.os.asset-extension }}" grafbabe
      - name: Upload asset to release
        if: github.event.release
        uses: shogo82148/actions-upload-release-asset@8dbaa4469aa7256e70624d72f2567fac8f5341b3
        with:
          asset_path: target/release/*.${{ matrix.os.asset-extension }}
          asset_content_type: application/octet-stream
          upload_url: ${{ github.event.release.upload_url }}
